config/routes.rb
Rails.application.routes.draw do

 



  get 'new/index'

  
  



  get 'rules/new'

  get 'rules/index'

  get 'rules/edit'

  get 'rules/show'


  devise_for :admins
  get 'documents/index'

  get 'documents/new'

  get 'documents/show'

  get 'documents/edit'

  get 'comman_bills/index'

  get 'comman_bills/new'

  get 'comman_bills/edit'

  get 'comman_bills/show'


  get 'nr_incomes/index'

  get 'nr_incomes/show'

  get 'nr_incomes/edit'

  get 'nr_incomes/new'
  get 'acc_payments/index'

  get 'acc_payments/new'

  get 'acc_payments/show'

  get 'acc_payments/edit'



  get 'penalty_charges/index'

  get 'penalty_charges/new'

  get 'penalty_charges/edit'

  get 'penalty_charges/show'




  get 'posts/index'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

scope "/admin" do
  resources :users
end
  get 'maintainnance_invoices/index'

  get 'maintainnance_invoices/new'

  get 'maintainnance_invoices/edit'

  get 'maintainnance_invoices/show'
  
  get 'penalty_charges/index'

  get 'penalty_charges/new'

  get 'penalty_charges/edit'

  get 'penalty_charges/show'

  get 'attenvendors/index'

  get 'classifieds/index'

  get 'classifieds/edit'


  get 'noticeboards/display'

  get 'noticeboards/new'

  get 'classifieds/show'


  get 'classifieds/new'
  get 'attendances/index'

  get 'attendances/edit'

  get 'attendances/show'

  get 'attendances/new'

  get 'discountdetails/index'

  get 'discountdetails/edit'

  get 'discountdetails/show'

  get 'discountdetails/new'
  
  get 'visitors/services'
  get 'visitors/adminindex'
  get 'visitors/accountingindex'
  get 'visitors/eventnotice'

  get 'visitors/account'
  


  get 'visitors/features'
  get 'regowners/index'
 

   root to: 'visitors#index'
   #root to: 'users#index'


  get 'users/index'
  
 
  get 'eventnotice' => 'visitors#eventnotice'
  get 'instantpol' => 'visitors#instantpol'
  get 'membersearch' => 'visitors#membersearch'
 get 'visitors/upcomming_meeting'
get 'visitors/accountingindex'
get 'visitors/adminindex' 

   resources :pollings do
    member do
      put "like" => "pollings#upvote"
      put "unlike" => "pollings#downvote"
    end
  end


  resources :classifieds
  resources :rules

  resources :comitteemembers
  resources :meetings
  resources :noticeboards
  resources :vendors

  resources :maintenance_charges
  resources :memachivements

  resources :comman_bills

   resources :bankaccounts

   resources :attenvisitors
   resources :attenvendors
   resources :complaints


   resources :visitors

  resources :regtenants
  resources :parktenants
  resources :parkowners
  resources :regowners
  resources :flatowners
  resources :documents

  resources :maintainnance_invoices
  resources :penalty_charges

  resources :acc_payments
  resources :discountdetails


  resources :nr_incomes
resources :galleries
  resources :events
  resources :items

  resources :roles
  resources :galleryattachments
  resources :users
  resources :classifieds
  resources :posts do
    resources :comments
  end




end

app/models/flatowner.rb
# == Schema Information
#
# Table name: flatowners
#
#  id         :integer          not null, primary key
#  phasename  :string(255)
#  subphase   :string(255)
#  flatno     :integer
#  flattype   :string(255)
#  flatarea   :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Flatowner < ActiveRecord::Base
	belongs_to :regowners
	belongs_to :users
end

app/controllers/flatowners_controller.rb
class FlatownersController < ApplicationController
  def index

     @flatowners = Flatowner.all
     @user = User.all
  end

  def edit
    @flatowner=Flatowner.find(params[:id])
  end

  def show
  	@flatowner=Flatowner.find(params[:id])
  end

  def new
     @flatowner =Flatowner.new
  end

  def update
    @flatowner=Flatowner.find(params[:id])
    if @flatowner.update(flatowner_params)
 
      redirect_to @flatowner
    else
      render 'edit'
  end
end

  def create
  	@flatowner= Flatowner.new(flatowner_params)
     
  	if @flatowner.save
  	redirect_to @flatowner
  else
    render 'new'
  end
end

  
private
def flatowner_params
      params.require(:flatowner).permit(:phasename, :subphase, :flatno, :flattype, :flatarea, :user_id)
    end
end

app/helpers/flatowners_helper.rb
module FlatownersHelper
end

app/views/flatowners/edit.html.erb
<html lang="en">
<head>
<%= render 'layouts/accordion' %>

<div class="container" style="padding-top: 20px; padding-bottom: 25px; align=center">
  <%= form_for :flatowner, url: flatowner_path(@flatowner), :class=>"form-horizontal", :role=>"form", method: :patch  do |f| %>

 <div class="col-md-2 col-sm-6 col-xs-12">

      
    </div>


  <div class="row">
    <!-- left column -->
   
    <!-- edit form column -->
    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
      

       <div class="form-group">
          <label class="col-lg-3 control-label"></label>
          <div class="col-lg-8">
           <h3>Flat Details</h3>
          </div>
        </div>

       <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Phase name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_field :phasename , autofocus: true, :class => "form-control" , :placeholder=>"Enter phase name"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">SubPhase name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_field :subphase , autofocus: true, :class => "form-control" , :placeholder=>"Enter sub phase name"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Flat number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
             <%= f.number_field :flatno, autofocus: true, :class => "form-control" , :placeholder=>"Enter flat no"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Flat type:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_field :flattype , autofocus: true, :class => "form-control" , :placeholder=>"Enter sub flat type"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Flat area:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
             <%= f.number_field :flatarea, autofocus: true, :class => "form-control" , :placeholder=>"Enter flat area"%>
          </div>
        </div>

        <div class="form-group">
        
          <div class="col-md-8">
             <%= f.submit 'Update', :class=>"btn btn-primary"%>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/flatowners/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<%= render 'layouts/accordion' %>

         <div class="col-sm-9 col-md-9"><!-- Tuser list div starts here -->

    <meta charset="utf-8">
    <!-- This file has been downloaded from Bootsnipp.com. Enjoy! -->
    <title>Table with users - Bootsnipp.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
    <style type="text/css">
        
    </style>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
</head>
<body>
<div class="btn-toolbar">
    <button class="btn btn-primary">New User</button>
    <button class="btn">Import</button>
    <button class="btn">Export</button>
</div>
<div class="well">

<h1>Registered Flats</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Phase Name</th>
          <th>Sub Phase Name</th>
          <th>Flattype</th>
          <th>Flat number</th>
          <th style="width: 36px;"></th>
        </tr>
      </thead>
      <tbody>
       <% @flatowners.each do |flatowner| %>
      <tr>
        <td><%= flatowner.id%></td>
        <td><%= flatowner.phasename %></td>
        <td><%= flatowner.flattype %></td>
        <td><%= flatowner.flatno %></td>
        <td><%= link_to 'Show', flatowner %></td>
        <td><%= link_to 'Edit', edit_flatowner_path(flatowner) %></td>
      </tr>
    <% end %>
        
      </tbody>
    </table>
</div>
<div class="pagination">
    <ul>
        <li><a href="#">Prev</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">Next</a></li>
    </ul>
</div>
<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Delete Confirmation</h3>
    </div>
    <div class="modal-body">
        <p class="error-text">Are you sure you want to delete the user?</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        <button class="btn btn-danger" data-dismiss="modal">Delete</button>
    </div>
</div>
</div> <!-- userlist div ends here -->
    </div>
</div>



      
<script type="text/javascript">

</script>


 




  

app/views/flatowners/new.html.erb
<html lang="en">
<head>
<%= render 'layouts/accordion' %>

<div class="container" style="padding-top: 20px; padding-bottom: 25px; align=center">
  <%= form_for :flatowner, url: flatowners_path, :class=>"form-horizontal", :role=>"form" do |f| %>

 <div class="col-md-2 col-sm-6 col-xs-12">

      
    </div>


  <div class="row">
    <!-- left column -->
   
    <!-- edit form column -->
    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
      
       <div class="form-group">
          <label class="col-lg-3 control-label"></label>
          <div class="col-lg-8">
           <h3>Flat Details</h3>
          </div>
        </div>

       <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Phase name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_field :phasename , autofocus: true, :class => "form-control" , :placeholder=>"Enter phase name"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">SubPhase name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_field :subphase , autofocus: true, :class => "form-control" , :placeholder=>"Enter sub phase name"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Flat number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
             <%= f.number_field :flatno, autofocus: true, :class => "form-control" , :placeholder=>"Enter flat no"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Flat type:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_field :flattype , autofocus: true, :class => "form-control" , :placeholder=>"Enter sub flat type"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Flat area:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
             <%= f.number_field :flatarea, autofocus: true, :class => "form-control" , :placeholder=>"Enter flat area"%>
          </div>
        </div>

        <div class="form-group">
        
          <div class="col-md-8">
             <%= f.submit 'Register', :class=>"btn btn-primary"%>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/flatowners/show.html.erb
<html>
  <body>
  <br><br><br><br>
   <div class="container">
    <div class="jumbotron">

        <table class="table">

            <p>
            <tr>
              <td><strong>Id:</strong></td>
              <td><%= @flatowner.id %></td>
            </tr>
            </p>

            
            <p><tr>
              <td><strong>Phasename:</strong></td>
             <td> <%= @flatowner.phasename %></td>
            </tr></p>

            <p><tr>
              <td><strong>Subphase:</strong></td>
              <td><%= @flatowner.subphase %></td>
           </tr> </p>

            <p><tr>
              <td><strong>Flatno:</strong></td>
              <td><%= @flatowner.flatno %></td>
           </tr> </p>

            <p><tr>
              <td><strong>Flattype:</strong></td>
              <td><%= @flatowner.flattype %></td>
           </tr> </p>

            <p><tr>
              <td><strong>Flatarea:</strong></td>
              <td><%= @flatowner.flatarea %></td>
            </tr></p>

          
           
      </table>
<%= link_to 'Edit', edit_flatowner_path(@flatowner) %> |
<%= link_to 'Back', flatowners_path %>

</div>
</div>
</body>
</html>