config/routes.rb
Rails.application.routes.draw do

 



  get 'new/index'

  
  



  get 'rules/new'

  get 'rules/index'

  get 'rules/edit'

  get 'rules/show'


  devise_for :admins
  get 'documents/index'

  get 'documents/new'

  get 'documents/show'

  get 'documents/edit'

  get 'comman_bills/index'

  get 'comman_bills/new'

  get 'comman_bills/edit'

  get 'comman_bills/show'


  get 'nr_incomes/index'

  get 'nr_incomes/show'

  get 'nr_incomes/edit'

  get 'nr_incomes/new'
  get 'acc_payments/index'

  get 'acc_payments/new'

  get 'acc_payments/show'

  get 'acc_payments/edit'



  get 'penalty_charges/index'

  get 'penalty_charges/new'

  get 'penalty_charges/edit'

  get 'penalty_charges/show'




  get 'posts/index'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

scope "/admin" do
  resources :users
end
  get 'maintainnance_invoices/index'

  get 'maintainnance_invoices/new'

  get 'maintainnance_invoices/edit'

  get 'maintainnance_invoices/show'
  
  get 'penalty_charges/index'

  get 'penalty_charges/new'

  get 'penalty_charges/edit'

  get 'penalty_charges/show'

  get 'attenvendors/index'

  get 'classifieds/index'

  get 'classifieds/edit'


  get 'noticeboards/display'

  get 'noticeboards/new'

  get 'classifieds/show'


  get 'classifieds/new'
  get 'attendances/index'

  get 'attendances/edit'

  get 'attendances/show'

  get 'attendances/new'

  get 'discountdetails/index'

  get 'discountdetails/edit'

  get 'discountdetails/show'

  get 'discountdetails/new'
  
  get 'visitors/services'
  get 'visitors/adminindex'
  get 'visitors/accountingindex'
  get 'visitors/eventnotice'

  get 'visitors/account'
  


  get 'visitors/features'
  get 'regowners/index'
 

   root to: 'visitors#index'
   #root to: 'users#index'


  get 'users/index'
  
 
  get 'eventnotice' => 'visitors#eventnotice'
  get 'instantpol' => 'visitors#instantpol'
  get 'membersearch' => 'visitors#membersearch'
 get 'visitors/upcomming_meeting'
get 'visitors/accountingindex'
get 'visitors/adminindex' 

   resources :pollings do
    member do
      put "like" => "pollings#upvote"
      put "unlike" => "pollings#downvote"
    end
  end


  resources :classifieds
  resources :rules

  resources :comitteemembers
  resources :meetings
  resources :noticeboards
  resources :vendors

  resources :maintenance_charges
  resources :memachivements

  resources :comman_bills

   resources :bankaccounts

   resources :attenvisitors
   resources :attenvendors
   resources :complaints


   resources :visitors

  resources :regtenants
  resources :parktenants
  resources :parkowners
  resources :regowners
  resources :flatowners
  resources :documents

  resources :maintainnance_invoices
  resources :penalty_charges

  resources :acc_payments
  resources :discountdetails


  resources :nr_incomes
resources :galleries
  resources :events
  resources :items

  resources :roles
  resources :galleryattachments
  resources :users
  resources :classifieds
  resources :posts do
    resources :comments
  end




end

app/models/polling.rb
# == Schema Information
#
# Table name: pollings
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  email_id           :string(255)
#  wing               :string(255)
#  flatno             :integer
#  age                :integer
#  positiontype       :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Polling < ActiveRecord::Base
	has_attached_file :image, styles: {large:"600*600>",medium:"300*300>", thumb:"150*150#"}
     validates_attachment_content_type :image, content_type:/\Aimage\/.*\z/
     

     acts_as_votable
end
 

app/controllers/pollings_controller.rb
class PollingsController < ApplicationController
  before_action :set_polling, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /pollings
  # GET /pollings.json

  def index
    @pollings = Polling.all
  end

  # GET /pollings/1
  # GET /pollings/1.json
  def show

  end

  # GET /pollings/new
  def new
    @polling = Polling.new
  end

  # GET /pollings/1/edit
  def edit
  end

  # POST /pollings
  # POST /pollings.json
  def create
    @polling = Polling.new(polling_params)

    respond_to do |format|
      if @polling.save
        format.html { redirect_to @polling, notice: 'Polling was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /pollings/1
  # PATCH/PUT /pollings/1.json
  def update
    respond_to do |format|
      if @polling.update(polling_params)
        format.html { redirect_to @polling, notice: 'Polling was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /pollings/1
  # DELETE /pollings/1.json
  def destroy
    @polling.destroy
    respond_to do |format|
      format.html { redirect_to pollings_url, notice: 'Polling was successfully destroyed.' }
    end
  end

  def upvote
    @polling.upvote_from current_user
    redirect_to pollings_path
  end

  def downvote
    @polling.downvote_from current_user
    redirect_to pollings_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_polling
      @polling = Polling.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def polling_params
      params.require(:polling).permit(:name, :age, :positiontype, :email_id, :wing, :flatno, :image)
    end
end

app/helpers/pollings_helper.rb
module PollingsHelper
  
end

app/views/pollings/edit.html.erb
<html lang="en">
<head>
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-folder-close">
                            </span>Content</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-pencil text-primary"></span><a href="http://www.jquery2dotnet.com">Articles</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-flash text-success"></span><a href="http://www.jquery2dotnet.com">News</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-file text-info"></span><a href="http://www.jquery2dotnet.com">Newsletters</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-comment text-success"></span><a href="http://www.jquery2dotnet.com">Comments</a>
                                        <span class="badge">42</span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                            </span>Modules</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Invoices</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Shipments</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Tex</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">
                            </span>Account</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Change Password</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Notifications</a> <span class="label label-info">5</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Import/Export</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-trash text-danger"></span><a href="http://www.jquery2dotnet.com" class="text-danger">
                                            Delete Account</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-file">
                            </span>Reports</a>
                        </h4>
                    </div>
                    <div id="collapseFour" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-usd"></span><a href="http://www.jquery2dotnet.com">Sales</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-user"></span><a href="http://www.jquery2dotnet.com">Customers</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-tasks"></span><a href="http://www.jquery2dotnet.com">Products</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-shopping-cart"></span><a href="http://www.jquery2dotnet.com">Shopping Cart</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<div class="row">
    <!-- left column -->

    <!-- edit form column -->
    <div class="col-md-8 col-sm-2 col-xs-10 personal-info">
        <%= form_for (@polling) ,html: {multipart:true} do |f| %>

     <form class="form-horizontal" role="form">
        <h1>Polling</h1>


        <div class="form-group">
          <label class="col-lg-3 control-label">Image:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px" style=" padding-bottom: 18px">        
           <%= f.file_field :image, autofocus: true, :class => "form-control" %>
        </div>
        </div>

      
  
        <div class="form-group">
         <label class="col-lg-3 control-label"> Name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">        
             <%= f.text_field :name, :class=>"form-control"%>
           </div>
        </div>

         <div class="form-group">
            <label class="col-lg-3 control-label">age:</label>
             <div class="col-lg-8" style=" padding-bottom: 18px">
                <%= f.number_field :age, :class=>"form-control" %>
             </div>
         </div>

       

        <div class="form-group">
            <label class="col-lg-3 control-label">Email Id:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
             <%= f.text_field :email_id, :class=>"form-control" %>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label">Wing:</label>
           <div class="col-lg-8" style=" padding-bottom: 18px">
              <%= f.text_field :wing, :class=>"form-control" %>
           </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label">Flat No:</label>
           <div class="col-lg-8" style=" padding-bottom: 18px">
             <%= f.number_field :flatno, :class=>"form-control" %>
           </div>
        </div>

         <div class="form-group">
          <label class="col-lg-3 control-label">Position Type:</label>
          <div class="col-md-5" style=" padding-bottom: 18px">
                <%= f.select(:positiontype, options_for_select([['Chair person', 'Chair person'], ['Secretary', 'Secretary'], ['Type3', 'Type3'], ['Type4', 'Type4']])) %>
            </div>
        </div>
      
          
        <div class="form-group">
          <label class="col-md-3 control-label"></label>
           <div class="col-lg-8" style=" padding-bottom: 18px">
             <span></span>
              <%= f.submit 'Submit',:class=>"btn btn-primary" %>
           </div>
       </div>

  
  </form>
  <% end %>

</div>
  </div>

app/views/pollings/index.html.erb
<div class="container" style="width:1666px" >
  <div class="content">

    <div class="row">

    <div class="horizontal">

      <%= link_to 'New polling', new_polling_path %>
        <% @pollings.each do |polling| %>
            <div class="panel-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-7 col-md-8">


                                <div class="comment-text">
                                  <td><h3 align="center"><%= image_tag polling.image %></h3></td>
                                </div>
                               
                                <div class="comment-text">
                                  <td><h3 align="center"><%= polling.name %></h3></td>
                                </div>

                                <div class="comment-text">
                                  <td><h3 align="center"><%= polling.age %></h3></td>
                                </div>

                                <div class="comment-text">
                                 <td><h3 align="center"><%= polling.positiontype %></h3></td>
                                </div>

                                <div class="comment-text">
                                    <td><h5 align="center"><%= polling.email_id %></h5></td>
                                </div>
                                        

                                <div class="comment-text">
                                  <td><h3 align="center"><%= polling.wing %></h3></td>
                                </div>

                                <div class="comment-text">
                                  <td><h3 align="center"><%= polling.flatno %></h3></td>
                                </div> 

                            </div>

                        </div>

                  <div class="caption" style="text-align:center;">
                  <%= link_to like_polling_path(polling), class: "like",method: :put do %>
                      <button type="button" class="btn btn_info" aria-lable="Left Align">

</li>
                        <div class="caption" style="text-align:center;">
                       <%= link_to like_polling_path(polling), class: "like",method: :put do %>
                        <button type="button" class="btn btn_info" aria-lable="Left Align">
                        <span class="glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
                        <span class="badge"><%= polling.get_upvotes.size %></span>
                      </button>
                  <% end %>

                  <%= link_to unlike_polling_path(polling), class: "like",method: :put do %>
                      <button type="button" class="btn btn_info" aria-lable="Left Align">
                        <span class="glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
                        <span class="badge"><%= polling.get_downvotes.size %></span>
                      </button>
                  <% end %>
                  </div>     
                           
                    </li>
                </ul>
            </div>    
        <% end %>
                   
        </div>
       </div>
    </div>
  
 

app/views/pollings/new.html.erb
<%= render 'layouts/accordion' %>
<div class="row">
    <!-- left column -->

    <!-- edit form column -->
    <div class="col-md-8 col-sm-2 col-xs-10 personal-info">
        <%= form_for (@polling) ,html: {multipart:true} do |f| %>

     <form class="form-horizontal" role="form">
        <h1>Polling</h1>


        <div class="form-group">
          <label class="col-lg-3 control-label">Image:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px" style=" padding-bottom: 18px">        
           <%= f.file_field :image, autofocus: true, :class => "form-control" %>
          </div>
        </div>

      
  
        <div class="form-group">
         <label class="col-lg-3 control-label"> Name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">        
             <%= f.text_field :name, :class=>"form-control"%>
           </div>
        </div>

         <div class="form-group">
            <label class="col-lg-3 control-label">age:</label>
             <div class="col-lg-8" style=" padding-bottom: 18px">
                <%= f.number_field :age, :class=>"form-control" %>
             </div>
         </div>

       

        <div class="form-group">
            <label class="col-lg-3 control-label">Email Id:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
             <%= f.text_field :email_id, :class=>"form-control" %>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label">Wing:</label>
           <div class="col-lg-8" style=" padding-bottom: 18px">
              <%= f.text_field :wing, :class=>"form-control" %>
           </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label">Flat No:</label>
           <div class="col-lg-8" style=" padding-bottom: 18px">
             <%= f.number_field :flatno, :class=>"form-control" %>
           </div>
        </div>

         <div class="form-group">
          <label class="col-lg-3 control-label">Position Type:</label>
          <div class="col-md-5" style=" padding-bottom: 18px">
                <%= f.select(:positiontype, options_for_select([['Chair person', 'Chair person'], ['Secretary', 'Secretary'], ['Type3', 'Type3'], ['Type4', 'Type4']])) %>
            </div>
        </div>
      
          
        <div class="form-group">
           <div class="col-lg-8" style=" padding-bottom: 18px">
             <span></span>
              <%= f.submit 'Submit',:class=>"btn btn-primary" %>
           </div>
       </div>

  
  </form>
  <% end %>

    </div>
  </div>

app/views/pollings/show.html.erb
<div class="col-sm-9 col-md-9"><!-- Tuser list div starts here -->

    <meta charset="utf-8">
    <!-- This file has been downloaded from Bootsnipp.com. Enjoy! -->
    <title>Table with users - Bootsnipp.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
    <style type="text/css">
        
    </style>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>

<body>

      <h2>Polling</h2>
      
     

    <p><tr>
      <td><%= image_tag @polling.image.url(:medium) %></td>
    </tr></p>

<p>
  <strong>Name:</strong>
  <%= @polling.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @polling.age %>
</p>

<p>
  <strong>PositionType:</strong>
  <%= @polling.positiontype %>
</p>



<p>
  <strong>Email:</strong>
  <%= @polling.email_id %>
</p>

<p>
  <strong>Wing:</strong>
  <%= @polling.wing %>
</p>

<p>
  <strong>Flatno:</strong>
  <%= @polling.flatno %>
</p>


<%= link_to 'Edit', edit_polling_path(@polling) %> |
<%= link_to 'Back', pollings_path %>
</div>


      
<script type="text/javascript">

</script>
</body>