config/routes.rb
Rails.application.routes.draw do

 



  get 'new/index'

  
  



  get 'rules/new'

  get 'rules/index'

  get 'rules/edit'

  get 'rules/show'


  devise_for :admins
  get 'documents/index'

  get 'documents/new'

  get 'documents/show'

  get 'documents/edit'

  get 'comman_bills/index'

  get 'comman_bills/new'

  get 'comman_bills/edit'

  get 'comman_bills/show'


  get 'nr_incomes/index'

  get 'nr_incomes/show'

  get 'nr_incomes/edit'

  get 'nr_incomes/new'
  get 'acc_payments/index'

  get 'acc_payments/new'

  get 'acc_payments/show'

  get 'acc_payments/edit'



  get 'penalty_charges/index'

  get 'penalty_charges/new'

  get 'penalty_charges/edit'

  get 'penalty_charges/show'




  get 'posts/index'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

scope "/admin" do
  resources :users
end
  get 'maintainnance_invoices/index'

  get 'maintainnance_invoices/new'

  get 'maintainnance_invoices/edit'

  get 'maintainnance_invoices/show'
  
  get 'penalty_charges/index'

  get 'penalty_charges/new'

  get 'penalty_charges/edit'

  get 'penalty_charges/show'

  get 'attenvendors/index'

  get 'classifieds/index'

  get 'classifieds/edit'


  get 'noticeboards/display'

  get 'noticeboards/new'

  get 'classifieds/show'


  get 'classifieds/new'
  get 'attendances/index'

  get 'attendances/edit'

  get 'attendances/show'

  get 'attendances/new'

  get 'discountdetails/index'

  get 'discountdetails/edit'

  get 'discountdetails/show'

  get 'discountdetails/new'
  
  get 'visitors/services'
  get 'visitors/adminindex'
  get 'visitors/accountingindex'
  get 'visitors/eventnotice'

  get 'visitors/account'
  


  get 'visitors/features'
  get 'regowners/index'
 

   root to: 'visitors#index'
   #root to: 'users#index'


  get 'users/index'
  
 
  get 'eventnotice' => 'visitors#eventnotice'
  get 'instantpol' => 'visitors#instantpol'
  get 'membersearch' => 'visitors#membersearch'
 get 'visitors/upcomming_meeting'
get 'visitors/accountingindex'
get 'visitors/adminindex' 

   resources :pollings do
    member do
      put "like" => "pollings#upvote"
      put "unlike" => "pollings#downvote"
    end
  end


  resources :classifieds
  resources :rules

  resources :comitteemembers
  resources :meetings
  resources :noticeboards
  resources :vendors

  resources :maintenance_charges
  resources :memachivements

  resources :comman_bills

   resources :bankaccounts

   resources :attenvisitors
   resources :attenvendors
   resources :complaints


   resources :visitors

  resources :regtenants
  resources :parktenants
  resources :parkowners
  resources :regowners
  resources :flatowners
  resources :documents

  resources :maintainnance_invoices
  resources :penalty_charges

  resources :acc_payments
  resources :discountdetails


  resources :nr_incomes
resources :galleries
  resources :events
  resources :items

  resources :roles
  resources :galleryattachments
  resources :users
  resources :classifieds
  resources :posts do
    resources :comments
  end




end

app/models/attenvisitor.rb
# == Schema Information
#
# Table name: attenvisitors
#
#  id         :integer          not null, primary key
#  firstname  :string(255)
#  lastname   :string(255)
#  date       :date
#  timein     :time
#  timeout    :time
#  phasename  :string(255)
#  flatno     :integer
#  mobileno   :string(255)
#  address    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Attenvisitor < ActiveRecord::Base
end

app/controllers/attenvisitors_controller.rb
class AttenvisitorsController < ApplicationController
  def index

     @attenvisitors = Attenvisitor.all
  end

  def edit
    @attenvisitor=Attenvisitor.find(params[:id])
  end

  def show
  	@attenvisitor=Attenvisitor.find(params[:id])
  end

  def new
     @attenvisitor = Attenvisitor.new
  end

  def update
    @attenvisitor=Attenvisitor.find(params[:id])
    if @attenvisitor.update(attenvisitor_params)
 
      redirect_to @attenvisitor
    else
      render 'edit'
  end
end

  def create
  	@attenvisitor= Attenvisitor.new(attenvisitor_params)
  	if @attenvisitor.save
  	redirect_to @attenvisitor
  else
    render 'new'
  end
end

  
private
def attenvisitor_params
      params.require(:attenvisitor).permit(:firstname, :lastname, :date, :timein, :timeout, :phasename, :flatno, :mobileno, :address)
    end

end

app/helpers/attenvisitors_helper.rb
module AttenvisitorsHelper
end

app/views/attenvisitors/edit.html.erb
<html lang="en">
<head>
<%= render 'layouts/accordion' %>


 <div class="container" style="padding-top: 20px; padding-bottom: 25px; align=center">
  <%= form_for :attenvisitor, url: attenvisitor_path(@attenvisitor), :class=>"form-horizontal", :role=>"form", method: :patch do |f| %>

 
  <h1 class="col-md-8 col-sm-6 col-xs-8">Visitors Attendence</h1>
  <div class="row">
   
    
          <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
        <div class="form-group">
          <label class="col-lg-3 control-label"></label>
          <div class="col-lg-8">
           <h3>Daily Attendence</h3>
          </div>
        </div>
  
      


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">First name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
          <%= f.text_field :firstname, autofocus: true, :class => "form-control" , :placeholder=>"Enter firstname"%>
          </div>
        </div>
        
        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Last name:</label>
          <div class="col-lg-8"  style=" padding-bottom: 18px">
              <%= f.text_field :lastname, autofocus: true, :class => "form-control" , :placeholder=>"Enter lastname"%>
          </div>
        </div>
        
         
         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Phase Name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
           <%= f.text_field :phasename, autofocus: true, :class => "form-control" , :placeholder=>"Enter phase name"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Flat Number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
           <%= f.number_field :flatno, autofocus: true, :class => "form-control" , :placeholder=>"Enter Flat Number"%>
          </div>
        </div>

         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Mobile Number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
           <%= f.text_field :mobileno, autofocus: true, :class => "form-control" , :placeholder=>"Enter Mobile Number"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Visitors Address:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_area :address, :class=>"form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Date:</label>
          <div class="col-lg-8" style="text-align:left; padding-bottom: 18px">
           <%= f.date_select :date ,:class => "form-control"  %>
          </div>
        </div>

         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Time In:</label>
          <div class="col-lg-8" style="text-align:left; padding-bottom: 18px">
           <%= f.time_select :timein ,:ampm=>true,:class => "form-control"  %>
          </div>
        </div>

         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Time Out:</label>
          <div class="col-lg-8" style="text-align:left; padding-bottom: 18px">
           <%= f.time_select :timeout ,:ampm=>true,:class => "form-control"  %>
          </div>
        </div>


        <div class="form-group">
          <div class="col-md-8">
             <%= f.submit 'Update', :class=>"btn btn-primary"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/attenvisitors/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<%= render 'layouts/accordion' %>

         <div class="col-sm-9 col-md-9"><!-- Tuser list div starts here -->

    

<h1>Visitors List</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Visitor Name</th>
          <th>Date</th>
          <th>Time In</th>
          <th>Time Out</th>
          <th>Visiting Flat No</th>
          <th>Address</th>
          <th>Mobile no</th>
          <th style="width: 36px;"></th>
        </tr>
      </thead>
      <tbody>
       <% @attenvisitors.each do |attenvisitor| %>
      <tr>
        <td><%= attenvisitor.id%></td>
        <td><%= attenvisitor.firstname %></td>
        <td><%= attenvisitor.date %></td>
        <td><%= attenvisitor.timein %></td>
        <td><%= attenvisitor.timeout %></td>
        <td><%= attenvisitor.flatno %></td>
        <td><%= attenvisitor.address %></td>
        <td><%= attenvisitor.mobileno %></td>
        <td><%= link_to 'Show', attenvisitor %></td>
        <td><%= link_to 'Edit', edit_attenvisitor_path(attenvisitor) %></td>
      </tr>
    <% end %>
        
      </tbody>
    </table>
</div>


</div> <!-- userlist div ends here -->
    </div>
</div>



      
<script type="text/javascript">

</script>


 




  

app/views/attenvisitors/new.html.erb
<html lang="en">
<head>
<%= render 'layouts/accordion' %>

 <div class="container" style="padding-top: 20px; padding-bottom: 25px; align=center">
  <%= form_for :attenvisitor, url: attenvisitors_path, :class=>"form-horizontal", :role=>"form" do |f| %>

 
  <h1 class="col-md-8 col-sm-6 col-xs-8">Visitors Attendence</h1>
  <div class="row">
    <!-- left column -->
  
    <!-- edit form column -->
    
          <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
        <div class="form-group">
          <label class="col-lg-3 control-label"></label>
          <div class="col-lg-8">
           <h3>Daily Attendence</h3>
          </div>
        </div>
  
      


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">First name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
          <%= f.text_field :firstname, autofocus: true, :class => "form-control" , :placeholder=>"Enter firstname"%>
          </div>
        </div>
        
        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Last name:</label>
          <div class="col-lg-8"  style=" padding-bottom: 18px">
              <%= f.text_field :lastname, autofocus: true, :class => "form-control" , :placeholder=>"Enter lastname"%>
          </div>
        </div>
        
         
         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Phase Name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
           <%= f.text_field :phasename, autofocus: true, :class => "form-control" , :placeholder=>"Enter phase name"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Flat Number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
           <%= f.number_field :flatno, autofocus: true, :class => "form-control" , :placeholder=>"Enter Flat Number"%>
          </div>
        </div>

         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Mobile Number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
           <%= f.text_field :mobileno, autofocus: true, :class => "form-control" , :placeholder=>"Enter Mobile Number"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Visitors Address:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_area :address, :class=>"form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Date:</label>
          <div class="col-lg-8" style="text-align:left; padding-bottom: 18px">
           <%= f.date_select :date ,:class => "form-control"  %>
          </div>
        </div>

         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Time In:</label>
          <div class="col-lg-8" style="text-align:left; padding-bottom: 18px">
           <%= f.time_select :timein ,:ampm=>true,:class => "form-control"  %>
          </div>
        </div>

         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Time Out:</label>
          <div class="col-lg-8" style="text-align:left; padding-bottom: 18px">
           <%= f.time_select :timeout ,:ampm=>true,:class => "form-control"  %>
          </div>
        </div>


        <div class="form-group">
          <div class="col-md-8">
             <%= f.submit 'Save', :class=>"btn btn-primary"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/attenvisitors/show.html.erb
<html>
  <body>
  <br><br><br><br>
   <div class="container">
    <div class="jumbotron">

        <table class="table">

            <p>
            <tr>
              <td><strong>Firstname Name:</strong></td>
              <td><%= @attenvisitor.firstname %></td>
            </tr>
            </p>

             <p>
            <tr>
              <td><strong>Lastname Name:</strong></td>
              <td><%= @attenvisitor.lastname %></td>
            </tr>
            </p>

            <p><tr>
              <td><strong>Date:</strong></td>
             <td> <%= @attenvisitor.date %></td>
           </tr> </p>


            <p><tr>
              <td><strong>Time IN:</strong></td>
              <td><%= @attenvisitor.timein %></td>
           </tr></p>

           <p><tr>
              <td><strong>Time Out:</strong></td>
              <td><%= @attenvisitor.timeout %></td>
           </tr></p>

             <p><tr>
              <td><strong>Phase Name:</strong></td>
              <td><%= @attenvisitor.phasename %></td>
           </tr></p>

             <p><tr>
              <td><strong>Flat Number:</strong></td>
              <td><%= @attenvisitor.flatno %></td>
           </tr></p>

            <p><tr>
              <td><strong>Mobile no:</strong></td>
              <td><%= @attenvisitor.mobileno %></td>
           </tr></p>

             <p><tr>
              <td><strong>Address:</strong></td>
              <td><%= @attenvisitor.address %></td>
           </tr></p>


        </table>
<%= link_to 'Edit', edit_attenvisitor_path(@attenvisitor) %> |
<%= link_to 'Back', attenvisitors_path %>

</div>
</div>
</body>
</html>