config/routes.rb
Rails.application.routes.draw do

 



  get 'new/index'

  
  



  get 'rules/new'

  get 'rules/index'

  get 'rules/edit'

  get 'rules/show'


  devise_for :admins
  get 'documents/index'

  get 'documents/new'

  get 'documents/show'

  get 'documents/edit'

  get 'comman_bills/index'

  get 'comman_bills/new'

  get 'comman_bills/edit'

  get 'comman_bills/show'


  get 'nr_incomes/index'

  get 'nr_incomes/show'

  get 'nr_incomes/edit'

  get 'nr_incomes/new'
  get 'acc_payments/index'

  get 'acc_payments/new'

  get 'acc_payments/show'

  get 'acc_payments/edit'



  get 'penalty_charges/index'

  get 'penalty_charges/new'

  get 'penalty_charges/edit'

  get 'penalty_charges/show'




  get 'posts/index'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

scope "/admin" do
  resources :users
end
  get 'maintainnance_invoices/index'

  get 'maintainnance_invoices/new'

  get 'maintainnance_invoices/edit'

  get 'maintainnance_invoices/show'
  
  get 'penalty_charges/index'

  get 'penalty_charges/new'

  get 'penalty_charges/edit'

  get 'penalty_charges/show'

  get 'attenvendors/index'

  get 'classifieds/index'

  get 'classifieds/edit'


  get 'noticeboards/display'

  get 'noticeboards/new'

  get 'classifieds/show'


  get 'classifieds/new'
  get 'attendances/index'

  get 'attendances/edit'

  get 'attendances/show'

  get 'attendances/new'

  get 'discountdetails/index'

  get 'discountdetails/edit'

  get 'discountdetails/show'

  get 'discountdetails/new'
  
  get 'visitors/services'
  get 'visitors/adminindex'
  get 'visitors/accountingindex'
  get 'visitors/eventnotice'

  get 'visitors/account'
  


  get 'visitors/features'
  get 'regowners/index'
 

   root to: 'visitors#index'
   #root to: 'users#index'


  get 'users/index'
  
 
  get 'eventnotice' => 'visitors#eventnotice'
  get 'instantpol' => 'visitors#instantpol'
  get 'membersearch' => 'visitors#membersearch'
 get 'visitors/upcomming_meeting'
get 'visitors/accountingindex'
get 'visitors/adminindex' 

   resources :pollings do
    member do
      put "like" => "pollings#upvote"
      put "unlike" => "pollings#downvote"
    end
  end


  resources :classifieds
  resources :rules

  resources :comitteemembers
  resources :meetings
  resources :noticeboards
  resources :vendors

  resources :maintenance_charges
  resources :memachivements

  resources :comman_bills

   resources :bankaccounts

   resources :attenvisitors
   resources :attenvendors
   resources :complaints


   resources :visitors

  resources :regtenants
  resources :parktenants
  resources :parkowners
  resources :regowners
  resources :flatowners
  resources :documents

  resources :maintainnance_invoices
  resources :penalty_charges

  resources :acc_payments
  resources :discountdetails


  resources :nr_incomes
resources :galleries
  resources :events
  resources :items

  resources :roles
  resources :galleryattachments
  resources :users
  resources :classifieds
  resources :posts do
    resources :comments
  end




end

app/models/regtenant.rb
# == Schema Information
#
# Table name: regtenants
#
#  id                 :integer          not null, primary key
#  ownerid            :integer
#  firstname          :string(255)
#  lastname           :string(255)
#  landlineno         :string(255)
#  mobileno           :string(255)
#  dob                :date
#  age                :integer
#  gender             :string(255)
#  nooffamily         :integer
#  profession         :string(255)
#  pancardno          :string(255)
#  address            :text
#  email              :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Regtenant < ActiveRecord::Base
	has_attached_file :image, styles: {large:"600*600>",medium:"300*300>", thumb:"150*150#"}
     validates_attachment_content_type :image, content_type:/\Aimage\/.*\z/
end

app/controllers/regtenants_controller.rb
class RegtenantsController < ApplicationController

  def index
  
     @regtenants = Regtenant.all
  end

  def edit
       @regtenant=Regtenant.find(params[:id])
  end

  def show
  	@regtenant=Regtenant.find(params[:id])
  end

  def new
    @regtenant=Regtenant.new
  end

 def update
    @regtenant=Regtenant.find(params[:id])
    if @regtenant.update(regtenant_params)
 
      redirect_to @regtenant
    else
      render 'edit'
  end
end

  def create
  	@regtenant= Regtenant.new(regtenant_params)
  	if @regtenant.save
  	 redirect_to @regtenant
    else
      render 'new'
  end
end
  
private
def regtenant_params
      params.require(:regtenant).permit(:ownerid,:firstname, :lastname, :email, :landlineno, :mobileno, :dob, :gender, :age, :nooffamily, :profession, :pancardno, :address,:image)
    end
end

app/helpers/regtenants_helper.rb
module RegtenantsHelper
end

app/views/regtenants/edit.html.erb
<html lang="en">
<head>
<%= render 'layouts/accordion' %>


 <div class="container" style="padding-top: 20px; padding-bottom: 25px; align=center">
   <%= form_for :regtenant, url: regtenant_path(@regtenant), :class=>"form-horizontal", :role=>"form", html: {multipart:true} , method: :patch do |f| %>

  <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="text-center" style="padding-left:87px" >
        <img src="http://lorempixel.com/200/200/people/9/" class="avatar img-circle img-thumbnail" alt="avatar">
        <h6>Upload a different photo...</h6>
   <%= f.file_field :image, autofocus: true, :class => "form-control" %>
      </div>
    </div>

  <h1 class="col-md-8 col-sm-6 col-xs-8">Tenant Registration</h1>
  <div class="row">
    <!-- left column -->
  
    <!-- edit form column -->
    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
 
        
        <div class="form-group">
          <label class="col-lg-3 control-label"></label>
          <div class="col-lg-8">
           <h3>Personal Information</h3>
          </div>
        </div>
  
      <div class="form-group">
          <label class="col-lg-3 control-label"  style="text-align:left">Owner Id</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
             <%= f.number_field :ownerid, autofocus: true, :class => "form-control" , :placeholder=>"Enter Owner Id"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">First name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
          <%= f.text_field :firstname, autofocus: true, :class => "form-control" , :placeholder=>"Enter firstname"%>
          </div>
        </div>
        
        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Last name:</label>
          <div class="col-lg-8"  style=" padding-bottom: 18px">
              <%= f.text_field :lastname, autofocus: true, :class => "form-control" , :placeholder=>"Enter lastname"%>
          </div>
        </div>
        
         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Email Id:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
              <%= f.email_field :email, autofocus: true, :class => "form-control" , :placeholder=>"Enter email"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Landline Number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
           <%= f.text_field :landlineno, autofocus: true, :class => "form-control" , :placeholder=>"Enter landline Number"%>
          </div>
        </div>

         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Mobile Number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
           <%= f.text_field :mobileno, autofocus: true, :class => "form-control" , :placeholder=>"Enter Mobile Number"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Date of birth:</label>
          <div class="col-lg-8" style="text-align:left; padding-bottom: 18px">
           <%= f.date_select :dob ,:class => "form-control"  %>
          </div>
        </div>
        
        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Age:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.number_field :age, autofocus: true, :class => "form-control" , :placeholder=>"Enter age"%>
          </div>
        </div>
        
         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Number of family members:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.number_field :nooffamily, autofocus: true, :class => "form-control" , :placeholder=>"Enter number of members"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Profession:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_field :profession, autofocus: true, :class => "form-control" , :placeholder=>"Enter profession"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Pancard Number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_field :pancardno, autofocus: true, :class => "form-control" , :placeholder=>"Enter pancard Number"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Permament Address:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_area :address, :class=>"form-control" %>
          </div>
        </div>

        
        
       <div class="form-group" >
          <label class="col-lg-3 control-label" style="text-align:left">Gender:</label>
          <div class="col-lg-3" style="text-align:left; padding-bottom: 18px">
            <%= radio_button :regtenant, :gender, :Male%>Male
            <%= radio_button :regtenant, :gender, :Female%>Female
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-8">
             <%= f.submit 'Update', :class=>"btn btn-primary"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/regtenants/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<%= render 'layouts/accordion' %>

         <div class="col-sm-9 col-md-9"><!-- Tuser list div starts here -->

    <meta charset="utf-8">
    <!-- This file has been downloaded from Bootsnipp.com. Enjoy! -->
    <title>Table with users - Bootsnipp.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
    <style type="text/css">
        
    </style>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
</head>
<body>
<div class="btn-toolbar">
    <button class="btn btn-primary">New User</button>
    <button class="btn">Import</button>
    <button class="btn">Export</button>
</div>
<div class="well">

<h1>Registered Tenants</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Mobile Name</th>
          <th>Owner Id</th>
          <th style="width: 36px;"></th>
        </tr>
      </thead>
      <tbody>
       <% @regtenants.each do |regtenant| %>
      <tr>
        <td><%= regtenant.id%></td>
        <td><%= regtenant.firstname %></td>
        <td><%= regtenant.lastname %></td>
        <td><%= regtenant.mobileno %></td>
        <td><%= regtenant.ownerid %></td>
        <td><%= link_to 'Show', regtenant %></td>
        <td><%= link_to 'Edit', edit_regtenant_path(regtenant) %></td>
      </tr>
    <% end %>
        
      </tbody>
    </table>
</div>
<div class="pagination">
    <ul>
        <li><a href="#">Prev</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">Next</a></li>
    </ul>
</div>
<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Delete Confirmation</h3>
    </div>
    <div class="modal-body">
        <p class="error-text">Are you sure you want to delete the user?</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        <button class="btn btn-danger" data-dismiss="modal">Delete</button>
    </div>
</div>
</div> <!-- userlist div ends here -->
    </div>
</div>



      
<script type="text/javascript">

</script>


 




  

app/views/regtenants/new.html.erb
<html lang="en">
<head>
<%= render 'layouts/accordion' %>


 <div class="container" style="padding-top: 20px; padding-bottom: 25px; align=center">
  <%= form_for :regtenant, url: regtenants_path, :class=>"form-horizontal", :role=>"form" ,html: {multipart:true} do |f| %>

  <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="text-center" style="padding-left:87px" >
        <img src="http://lorempixel.com/200/200/people/9/" class="avatar img-circle img-thumbnail" alt="avatar">
        <h6>Upload a different photo...</h6>
     <%= f.file_field :image, autofocus: true, :class => "form-control" %>
      </div>
    </div>

  <h1 class="col-md-8 col-sm-6 col-xs-8">Tenant Registration</h1>
  <div class="row">
    <!-- left column -->
  
    <!-- edit form column -->
    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
      
        <div class="form-group">
          <label class="col-lg-3 control-label"></label>
          <div class="col-lg-8">
           <h3>Personal Information</h3>
          </div>
        </div>
  
      <div class="form-group">
          <label class="col-lg-3 control-label"  style="text-align:left">Owner Id</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
             <%= f.number_field :ownerid, autofocus: true, :class => "form-control" , :placeholder=>"Enter Owner Id"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">First name:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
          <%= f.text_field :firstname, autofocus: true, :class => "form-control" , :placeholder=>"Enter firstname"%>
          </div>
        </div>
        
        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Last name:</label>
          <div class="col-lg-8"  style=" padding-bottom: 18px">
              <%= f.text_field :lastname, autofocus: true, :class => "form-control" , :placeholder=>"Enter lastname"%>
          </div>
        </div>
        
         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Email Id:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
              <%= f.email_field :email, autofocus: true, :class => "form-control" , :placeholder=>"Enter email"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Landline Number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
           <%= f.text_field :landlineno, autofocus: true, :class => "form-control" , :placeholder=>"Enter landline Number"%>
          </div>
        </div>

         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Mobile Number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
           <%= f.text_field :mobileno, autofocus: true, :class => "form-control" , :placeholder=>"Enter Mobile Number"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Date of birth:</label>
          <div class="col-lg-8" style="text-align:left; padding-bottom: 18px">
           <%= f.date_select :dob ,:class => "form-control"  %>
          </div>
        </div>
        
        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Age:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.number_field :age, autofocus: true, :class => "form-control" , :placeholder=>"Enter age"%>
          </div>
        </div>
        
         <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Number of family members:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.number_field :nooffamily, autofocus: true, :class => "form-control" , :placeholder=>"Enter number of members"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Profession:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_field :profession, autofocus: true, :class => "form-control" , :placeholder=>"Enter profession"%>
          </div>
        </div>


        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Pancard Number:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_field :pancardno, autofocus: true, :class => "form-control" , :placeholder=>"Enter pancard Number"%>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label" style="text-align:left">Permament Address:</label>
          <div class="col-lg-8" style=" padding-bottom: 18px">
            <%= f.text_area :address, :class=>"form-control" %>
          </div>
        </div>
        
       <div class="form-group" >
          <label class="col-lg-3 control-label" style="text-align:left">Gender:</label>
          <div class="col-lg-3" style="text-align:left; padding-bottom: 18px">
            <%= radio_button :regtenant, :gender, :Male%>Male
            <%= radio_button :regtenant, :gender, :Female%>Female
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-8">
             <%= f.submit 'Register', :class=>"btn btn-primary"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/regtenants/show.html.erb
<html>
  <body>
  <br><br><br><br>
   <div class="container">
    <div class="jumbotron">


        <table class="table">
            <p><tr>
                  <td><strong>Image:</strong></td>
                  <td><%= image_tag  @regtenant.image.url(:medium) %></td>
                </tr></p>
            <p>
            <p>
            <tr>
              <td><strong>Firstname:</strong></td>
              <td><%= @regtenant.firstname %></td>
            </tr>
            </p>

            <p><tr>
              <td><strong>Lastname:</strong></td>
              <td><%= @regtenant.lastname %></td>
            </tr></p>


            <p><tr>
              <td><strong>Email:</strong></td>
              <td><%= @regtenant.email %></td>
            </tr></p>

            <p><tr>
              <td><strong>Landlineno:</strong></td>
              <td><%= @regtenant.landlineno %></td>
           </tr> </p>

            <p><tr>
             <td><strong>Mobileno:</strong></td>
             <td> <%= @regtenant.mobileno %></td>
           </tr> </p>

            <p><tr>
              <td><strong>Dob:</strong></td>
             <td> <%= @regtenant.dob %></td>
           </tr> </p>

            <p><tr>
              <td><strong>Gender:</strong></td>
              <td><%= @regtenant.gender %></td>
            </tr></p>

            <p><tr>
              <td><strong>Age:</strong></td>
              <td><%= @regtenant.age %></td>
           </tr> </p>

            <p><tr>
              <td><strong>Nooffamily:</strong></td>
              <td><%= @regtenant.nooffamily %></td>
            </tr></p>

            <p><tr>
              <td><strong>Profession:</strong></td>
              <td><%= @regtenant.profession %></td>
           </tr> </p>

            <p><tr>
              <td><strong>Pancardno:</strong></td>
              <td><%= @regtenant.pancardno %></td>
            </tr></p>

            <p><tr>
              <td><strong>Address:</strong></td>
              <td><%= @regtenant.address %></td>
           </tr></p>

          
        
      </table>
<%= link_to 'Edit', edit_regtenant_path(@regtenant) %> |
<%= link_to 'Back', regtenants_path %>

</div>
</div>
</body>
</html>